// Base de datos de cursos para NovaLearn
const COURSES_DATA = [
  {
    id: "1",
    titulo: "HTML5, CSS3 y JavaScript Moderno desde Cero a Pro",
    instructor: "Juan Pedro Martínez",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    categoria: "desarrollo",
    imagen: "img/curso1.jpg",
    precioOriginal: 200,
    precioOferta: 15,
    rating: 4.9,
    reviews: 2430,
    estudiantes: 18450,
    nivel: "Principiante - Avanzado",
    duracion: "42 horas",
    badge: "Bestseller",
    descripcion: "Domina el desarrollo frontend moderno construyendo proyectos reales paso a paso con las tecnologías fundamentales de la web."
  },
  {
    id: "2",
    titulo: "Cocina Vegetariana y Nutrición Saludable Gourmet",
    instructor: "Chef Elena Rostova",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80",
    categoria: "estilo-vida",
    imagen: "img/curso2.jpg",
    precioOriginal: 180,
    precioOferta: 15,
    rating: 4.8,
    reviews: 1250,
    estudiantes: 8920,
    nivel: "Todos los niveles",
    duracion: "18 horas",
    badge: "Destacado",
    descripcion: "Aprende recetas deliciosas, técnicas culinarias de vanguardia y balance de nutrientes sin complicaciones en casa."
  },
  {
    id: "3",
    titulo: "Guitarra Eléctrica y Acústica: De Principiante a Solista",
    instructor: "Carlos Santana V.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    categoria: "musica",
    imagen: "img/curso3.jpg",
    precioOriginal: 220,
    precioOferta: 15,
    rating: 4.9,
    reviews: 3100,
    estudiantes: 15200,
    nivel: "Principiante",
    duracion: "28 horas",
    badge: "Popular",
    descripcion: "Técnica, digitación, armonía y solos inolvidables. Aprende tus canciones favoritas con métodos prácticos y divertidos."
  },
  {
    id: "4",
    titulo: "Huerto Urbano Sostenible: Cultiva tus Propios Alimentos",
    instructor: "Dra. Sofía Morales",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80",
    categoria: "estilo-vida",
    imagen: "img/curso4.jpg",
    precioOriginal: 160,
    precioOferta: 15,
    rating: 4.7,
    reviews: 980,
    estudiantes: 6400,
    nivel: "Iniciación",
    duracion: "14 horas",
    badge: "Ecológico",
    descripcion: "Crea un huerto productivo en macetas, balcones o jardines pequeños sin pesticidas químicos y con máxima frescura."
  },
  {
    id: "5",
    titulo: "Decoración de Interiores y Diseño de Espacios Acogedores",
    instructor: "Arq. Mateo Valenzuela",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    categoria: "diseno",
    imagen: "img/curso5.jpg",
    precioOriginal: 190,
    precioOferta: 15,
    rating: 4.8,
    reviews: 1420,
    estudiantes: 9800,
    nivel: "Intermedio",
    duracion: "22 horas",
    badge: "Tendencia",
    descripcion: "Transforma cualquier habitación aplicando teoría del color, iluminación, texturas y distribución armónica del espacio."
  },
  {
    id: "6",
    titulo: "Inteligencia Artificial y Machine Learning con Python",
    instructor: "Dr. Roberto Céspedes",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&auto=format&fit=crop&q=80",
    categoria: "desarrollo",
    imagen: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    precioOriginal: 250,
    precioOferta: 19,
    rating: 5.0,
    reviews: 4210,
    estudiantes: 23100,
    nivel: "Intermedio - Avanzado",
    duracion: "55 horas",
    badge: "Top Ventas",
    descripcion: "Crea modelos predictivos, redes neuronales, visión por computadora y aplicaciones de IA Generativa de última generación."
  },
  {
    id: "7",
    titulo: "Diseño UI/UX con Figma: De Wireframes a Prototipos Interactivos",
    instructor: "Camila Navarro",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    categoria: "diseno",
    imagen: "https://images.unsplash.com/photo-1581291518655-9523c932deda?w=600&auto=format&fit=crop&q=80",
    precioOriginal: 210,
    precioOferta: 15,
    rating: 4.9,
    reviews: 2840,
    estudiantes: 14750,
    nivel: "Principiante a Pro",
    duracion: "36 horas",
    badge: "Bestseller",
    descripcion: "Aprende el sistema de diseño completo en Figma, micro-interacciones, testing de usabilidad y entregables profesionales para desarrollo."
  },
  {
    id: "8",
    titulo: "Estrategias de Marketing Digital y Growth Hacking 2026",
    instructor: "Lucas Benítez",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
    categoria: "negocios",
    imagen: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
    precioOriginal: 195,
    precioOferta: 15,
    rating: 4.8,
    reviews: 1890,
    estudiantes: 11200,
    nivel: "Todos los niveles",
    duracion: "30 horas",
    badge: "Nuevo",
    descripcion: "Multiplica las ventas de cualquier negocio con embudos automatizados, SEO técnico, anuncios de alto rendimiento y analítica avanzada."
  },
  {
    id: "9",
    titulo: "Producción Musical y Mezcla en Ableton Live",
    instructor: "DJ & Productor Kaelen",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80",
    categoria: "musica",
    imagen: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80",
    precioOriginal: 230,
    precioOferta: 18,
    rating: 4.9,
    reviews: 1670,
    estudiantes: 8700,
    nivel: "Intermedio",
    duracion: "34 horas",
    badge: "Destacado",
    descripcion: "Crea beats, sintetiza sonidos únicos, masteriza tus pistas con calidad de estudio discográfico y lánzalas a Spotify."
  },
  {
    id: "10",
    titulo: "Fullstack React 19, Next.js y Node.js para Producción",
    instructor: "David Morales",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    categoria: "desarrollo",
    imagen: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80",
    precioOriginal: 270,
    precioOferta: 19,
    rating: 5.0,
    reviews: 5120,
    estudiantes: 28900,
    nivel: "Avanzado",
    duracion: "60 horas",
    badge: "Top Ventas",
    descripcion: "Construye aplicaciones web escalables con Server Components, autenticación robusta, bases de datos PostgreSQL y despliegue continuo."
  },
  {
    id: "11",
    titulo: "Finanzas Personales e Inversiones Inteligentes",
    instructor: "Lic. Valeria Quiroga",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&auto=format&fit=crop&q=80",
    categoria: "negocios",
    imagen: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=600&auto=format&fit=crop&q=80",
    precioOriginal: 175,
    precioOferta: 15,
    rating: 4.8,
    reviews: 2130,
    estudiantes: 13400,
    nivel: "Principiante",
    duracion: "20 horas",
    badge: "Popular",
    descripcion: "Domina tu flujo de caja, elimina deudas, comprende fondos indexados y genera ingresos pasivos con fundamentos sólidos."
  },
  {
    id: "12",
    titulo: "Fotografía Profesional y Retoque Digital con Lightroom",
    instructor: "Sebastián Cruz",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    categoria: "diseno",
    imagen: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=600&auto=format&fit=crop&q=80",
    precioOriginal: 185,
    precioOferta: 15,
    rating: 4.9,
    reviews: 1750,
    estudiantes: 9200,
    nivel: "Principiante a Intermedio",
    duracion: "26 horas",
    badge: "Nuevo",
    descripcion: "Aprende composición visual, manejo manual de cámaras réflex y mirrorless, y colorimetría profesional para cine y fotografía."
  }
];
